import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarDays, ChevronDown, Clock3, GripVertical, RefreshCw } from 'lucide-react'
import { getTimetable, updateTimetable, type TimetableEntry } from '../../services/timetable'
import './timetable.css'

const days = [{ value: 1, label: 'Monday', short: 'Mon' }, { value: 2, label: 'Tuesday', short: 'Tue' }, { value: 3, label: 'Wednesday', short: 'Wed' }, { value: 4, label: 'Thursday', short: 'Thu' }, { value: 5, label: 'Friday', short: 'Fri' }]
const slots = ['08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00']
function displayRef(value: unknown, fallback: string) { if (!value) return fallback; if (typeof value === 'string') return value.slice(-6); const object = value as { name?: string; code?: string; firstName?: string; lastName?: string }; return object.name ?? object.code ?? ([object.firstName, object.lastName].filter(Boolean).join(' ') || fallback) }
function toMinutes(value: string) { const [hours, minutes] = value.split(':').map(Number); return hours * 60 + minutes }
function addHour(value: string) { const minutes = toMinutes(value) + 60; return `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}` }

export function TimetablePage() {
  const queryClient = useQueryClient(); const [academicYear, setAcademicYear] = useState('2025-2026'); const [dragged, setDragged] = useState<TimetableEntry | null>(null); const [conflictCell, setConflictCell] = useState(''); const [notice, setNotice] = useState('')
  const query = useQuery({ queryKey: ['timetable', academicYear], queryFn: () => getTimetable({ academicYear }) })
  const moveMutation = useMutation({ mutationFn: ({ entry, dayOfWeek, startTime }: { entry: TimetableEntry; dayOfWeek: number; startTime: string }) => updateTimetable(entry._id, { dayOfWeek, startTime, endTime: addHour(startTime) }), onSuccess: () => { setNotice('Class moved successfully.'); setConflictCell(''); void queryClient.invalidateQueries({ queryKey: ['timetable', academicYear] }) }, onError: (error: unknown, variables) => { setConflictCell(`${variables.dayOfWeek}-${variables.startTime}`); setNotice(error instanceof Error ? error.message : 'This class conflicts with another booking.') } })
  const entries = query.data ?? []; const entriesByCell = useMemo(() => { const map = new Map<string, TimetableEntry[]>(); entries.forEach((entry) => { const key = `${entry.dayOfWeek}-${entry.startTime}`; map.set(key, [...(map.get(key) ?? []), entry]) }); return map }, [entries])
  const handleDrop = (dayOfWeek: number, startTime: string) => { if (!dragged) return; moveMutation.mutate({ entry: dragged, dayOfWeek, startTime }); setDragged(null) }
  return <div className="timetable-page"><header className="timetable-heading"><div><p className="timetable-eyebrow">Academics / Timetable</p><h1>Weekly timetable</h1><p>Move classes across the week and keep scheduling conflicts visible.</p></div><div className="timetable-actions"><label className="year-select"><CalendarDays size={15} /><select value={academicYear} onChange={(event) => setAcademicYear(event.target.value)}><option>2025-2026</option><option>2026-2027</option></select><ChevronDown size={13} /></label><button className="timetable-refresh" type="button" onClick={() => query.refetch()}><RefreshCw size={15} /> Refresh</button></div></header>{notice && <div className={`timetable-notice ${conflictCell ? 'timetable-notice--error' : ''}`}><span>{notice}</span><button type="button" onClick={() => { setNotice(''); setConflictCell('') }}>Dismiss</button></div>}<section className="timetable-panel"><div className="timetable-legend"><span><i className="legend-dot legend-dot--blue" /> Scheduled class</span><span><i className="legend-dot legend-dot--red" /> Conflict</span><span className="drag-hint"><GripVertical size={14} /> Drag a class to reschedule</span></div><div className="timetable-scroll"><div className="timetable-grid"><div className="timetable-corner"><Clock3 size={15} /></div>{days.map((day) => <div className="day-header" key={day.value}><strong>{day.short}</strong><span>{day.label}</span></div>)}{slots.map((slot) => <div className="timetable-row" key={slot}><div className="time-label">{slot}</div>{days.map((day) => { const key = `${day.value}-${slot}`; const cellEntries = entriesByCell.get(key) ?? []; return <div key={key} className={`time-cell ${conflictCell === key ? 'time-cell--conflict' : ''}`} onDragOver={(event) => event.preventDefault()} onDrop={() => handleDrop(day.value, slot)}>{cellEntries.map((entry) => <TimetableCard key={entry._id} entry={entry} onDragStart={() => setDragged(entry)} onDragEnd={() => setDragged(null)} />)}</div> })}</div>)}</div></div>{query.isLoading && <div className="timetable-loading">Loading timetable...</div>}{query.isError && <div className="timetable-loading">Unable to load the timetable. Check your connection and retry.</div>}</section></div>
}
function TimetableCard({ entry, onDragStart, onDragEnd }: { entry: TimetableEntry; onDragStart: () => void; onDragEnd: () => void }) { return <article className="timetable-card" draggable onDragStart={onDragStart} onDragEnd={onDragEnd}><GripVertical size={13} className="card-grip" /><strong>{displayRef(entry.subjectId, 'Subject')}</strong><span>{displayRef(entry.classId, 'Class')} {entry.sectionId ? `· ${displayRef(entry.sectionId, 'Section')}` : ''}</span><small>{entry.startTime} - {entry.endTime}{entry.room ? ` · ${entry.room}` : ''}</small></article> }
