import { Types } from 'mongoose'
import { Assignment } from '../models/Assignment.js'
import { AssignmentSubmission } from '../models/AssignmentSubmission.js'
import { AppError, asyncHandler } from '../utils/errors.js'

async function findAssignment(req: { auth?: { institutionId: string } }, id: string) { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const assignment = await Assignment.findOne({ _id: id, institutionId: req.auth.institutionId }); if (!assignment) throw new AppError('Assignment not found', 404, 'ASSIGNMENT_NOT_FOUND'); return assignment }
export const listAssignments = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const filter: Record<string, unknown> = { institutionId: new Types.ObjectId(req.auth.institutionId) }; if (req.query.classId) filter.classId = req.query.classId; if (req.query.status) filter.status = req.query.status; const data = await Assignment.find(filter).sort({ dueDate: 1 }).populate('subjectId', 'name code').populate('classId', 'name code').populate('teacherId', 'firstName lastName').lean(); res.json({ success: true, data }) })
export const createAssignment = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const assignment = await Assignment.create({ ...req.body, institutionId: req.auth.institutionId, teacherId: req.auth.userId }); res.status(201).json({ success: true, data: assignment }) })
export const updateAssignment = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const assignment = await Assignment.findOneAndUpdate({ _id: String(req.params.id), institutionId: req.auth.institutionId }, { $set: req.body }, { new: true, runValidators: true }).lean(); if (!assignment) throw new AppError('Assignment not found', 404, 'ASSIGNMENT_NOT_FOUND'); res.json({ success: true, data: assignment }) })
export const deleteAssignment = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const assignment = await Assignment.findOneAndUpdate({ _id: String(req.params.id), institutionId: req.auth.institutionId }, { $set: { status: 'closed' } }, { new: true }).lean(); if (!assignment) throw new AppError('Assignment not found', 404, 'ASSIGNMENT_NOT_FOUND'); res.json({ success: true, data: { id: req.params.id, status: 'closed' } }) })
export const submitAssignment = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const assignment = await findAssignment(req, String(req.params.id)); const submission = await AssignmentSubmission.findOneAndUpdate({ institutionId: req.auth.institutionId, assignmentId: assignment._id, studentId: req.auth.userId }, { $set: { ...req.body, institutionId: req.auth.institutionId, assignmentId: assignment._id, studentId: req.auth.userId, submittedAt: req.body.status === 'submitted' ? new Date() : undefined } }, { new: true, upsert: true, runValidators: true }).lean(); res.status(201).json({ success: true, data: submission }) })
export const listSubmissions = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); await findAssignment(req, String(req.params.id)); const data = await AssignmentSubmission.find({ institutionId: req.auth.institutionId, assignmentId: req.params.id }).populate('studentId', 'firstName lastName email').sort({ submittedAt: -1 }).lean(); res.json({ success: true, data }) })
export const gradeSubmission = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); await findAssignment(req, String(req.params.id)); const submission = await AssignmentSubmission.findOneAndUpdate({ _id: String(req.params.submissionId), institutionId: req.auth.institutionId, assignmentId: req.params.id }, { $set: { ...req.body, gradedBy: req.auth.userId, gradedAt: new Date() } }, { new: true, runValidators: true }).lean(); if (!submission) throw new AppError('Submission not found', 404, 'SUBMISSION_NOT_FOUND'); res.json({ success: true, data: submission }) })
