import { Types } from 'mongoose'
import { Exam } from '../models/Exam.js'
import { Marks } from '../models/Marks.js'
import { Result } from '../models/Result.js'
import { AppError, asyncHandler } from '../utils/errors.js'

function gradeFor(percentage: number) { if (percentage >= 90) return 'A+'; if (percentage >= 80) return 'A'; if (percentage >= 70) return 'B'; if (percentage >= 60) return 'C'; if (percentage >= 50) return 'D'; return 'F' }
function gpaFor(percentage: number) { return Math.round(Math.min(4, Math.max(0, percentage / 25)) * 100) / 100 }
async function findExam(req: { auth?: { institutionId: string } }, id: string) { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const exam = await Exam.findOne({ _id: id, institutionId: req.auth.institutionId }); if (!exam) throw new AppError('Exam not found', 404, 'EXAM_NOT_FOUND'); return exam }

export const listExams = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const filter: Record<string, unknown> = { institutionId: new Types.ObjectId(req.auth.institutionId) }; if (typeof req.query.status === 'string') filter.status = req.query.status; const data = await Exam.find(filter).sort({ startDate: -1 }).populate('subjects.subjectId', 'name code').lean(); res.json({ success: true, data }) })
export const createExam = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const exam = await Exam.create({ ...req.body, institutionId: req.auth.institutionId }); res.status(201).json({ success: true, data: exam }) })
export const updateExam = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const exam = await Exam.findOneAndUpdate({ _id: req.params.id, institutionId: req.auth.institutionId }, { $set: req.body }, { new: true, runValidators: true }).lean(); if (!exam) throw new AppError('Exam not found', 404, 'EXAM_NOT_FOUND'); res.json({ success: true, data: exam }) })
export const deleteExam = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const exam = await Exam.findOneAndUpdate({ _id: req.params.id, institutionId: req.auth.institutionId }, { $set: { status: 'closed' } }, { new: true }).lean(); if (!exam) throw new AppError('Exam not found', 404, 'EXAM_NOT_FOUND'); res.json({ success: true, data: { id: req.params.id, status: 'closed' } }) })
export const enterMarks = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const exam = await findExam(req, String(req.params.id)); const entries = req.body.entries as Array<{ studentId: string; subjectId: string; marks: number; maxMarks: number; remarks?: string }>; const operations = entries.map((entry) => ({ updateOne: { filter: { institutionId: new Types.ObjectId(req.auth!.institutionId), examId: exam._id, studentId: new Types.ObjectId(entry.studentId), subjectId: new Types.ObjectId(entry.subjectId) }, update: { $set: { ...entry, institutionId: new Types.ObjectId(req.auth!.institutionId), examId: exam._id, studentId: new Types.ObjectId(entry.studentId), subjectId: new Types.ObjectId(entry.subjectId), enteredBy: new Types.ObjectId(req.auth!.userId), grade: gradeFor((entry.marks / entry.maxMarks) * 100) } }, upsert: true } })); const result = await Marks.bulkWrite(operations); res.json({ success: true, data: { matched: result.matchedCount, upserted: result.upsertedCount, modified: result.modifiedCount } }) })
export const generateResults = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const exam = await findExam(req, String(req.params.id)); const rows = await Marks.aggregate([{ $match: { institutionId: new Types.ObjectId(req.auth.institutionId), examId: exam._id } }, { $group: { _id: '$studentId', totalMarks: { $sum: '$maxMarks' }, obtainedMarks: { $sum: '$marks' } } }]); const operations = rows.map((row) => { const percentage = row.totalMarks ? (row.obtainedMarks / row.totalMarks) * 100 : 0; return { updateOne: { filter: { institutionId: new Types.ObjectId(req.auth!.institutionId), examId: exam._id, studentId: row._id }, update: { $set: { institutionId: new Types.ObjectId(req.auth!.institutionId), examId: exam._id, studentId: row._id, totalMarks: row.totalMarks, obtainedMarks: row.obtainedMarks, percentage, gpa: gpaFor(percentage), grade: gradeFor(percentage), isPublished: false } }, upsert: true } } }); if (operations.length) await Result.bulkWrite(operations); res.json({ success: true, data: { generated: operations.length } }) })
export const listResults = asyncHandler(async (req, res) => { if (!req.auth) throw new AppError('Authentication required', 401, 'AUTH_REQUIRED'); const examId = String(req.params.id); await findExam(req, examId); const filter: Record<string, unknown> = { institutionId: new Types.ObjectId(req.auth.institutionId), examId: new Types.ObjectId(examId) }; if (typeof req.query.studentId === 'string') filter.studentId = new Types.ObjectId(req.query.studentId); const data = await Result.find(filter).populate('studentId', 'firstName lastName email').sort({ percentage: -1 }).lean(); res.json({ success: true, data }) })
