import { useRef, useState, type ChangeEvent, type FormEvent } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ChevronDown, ChevronLeft, ChevronRight, Download, Filter, LoaderCircle, Pencil, Plus, Search, Trash2, Upload, Users, X } from 'lucide-react'
import { createUser, deactivateUser, getUsers, updateUser, type UserFilters, type UserInput, type UserRecord } from '../../services/users'
import type { UserRole } from '../../store/authSlice'
import './users.css'

const roles: Array<UserRole | 'all'> = ['all', 'super_admin', 'principal', 'teacher', 'student', 'parent']
const roleLabels: Record<UserRole | 'all', string> = { all: 'All roles', super_admin: 'Super Admin', principal: 'Principal', teacher: 'Teacher', student: 'Student', parent: 'Parent' }
const initialFilters: UserFilters = { page: 1, limit: 10, search: '', role: 'all', isActive: 'all' }
const blankForm: UserFormValues = { firstName: '', lastName: '', email: '', phone: '', password: '', role: 'student' }
type UserFormValues = { firstName: string; lastName: string; email: string; phone: string; password: string; role: UserRole }

export function UserManagementPage() {
  const [filters, setFilters] = useState<UserFilters>(initialFilters)
  const [editingUser, setEditingUser] = useState<UserRecord | null>(null)
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [actionMessage, setActionMessage] = useState('')
  const importInput = useRef<HTMLInputElement>(null)
  const usersQuery = useQuery({ queryKey: ['users', filters], queryFn: () => getUsers(filters), placeholderData: (previous) => previous })
  const users = usersQuery.data?.data ?? []
  const meta = usersQuery.data?.meta
  const setFilter = <Key extends keyof UserFilters>(key: Key, value: UserFilters[Key]) => setFilters((current) => ({ ...current, [key]: value, ...(key === 'page' ? {} : { page: 1 }) }))
  const openCreate = () => { setEditingUser(null); setIsModalOpen(true) }
  const openEdit = (user: UserRecord) => { setEditingUser(user); setIsModalOpen(true) }
  const saveUser = async (input: UserInput) => { setIsSaving(true); try { if (editingUser) await updateUser(editingUser.id, input); else await createUser(input); setIsModalOpen(false); setActionMessage(editingUser ? 'User updated successfully.' : 'User created successfully.'); await usersQuery.refetch() } finally { setIsSaving(false) } }
  const removeUser = async (user: UserRecord) => { if (!window.confirm(`Deactivate ${user.firstName} ${user.lastName}?`)) return; await deactivateUser(user.id); setActionMessage('User deactivated.'); await usersQuery.refetch() }
  const importCsv = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; const rows = parseCsv(await file.text()); const imported = await Promise.allSettled(rows.map((row) => createUser({ firstName: row.firstName, lastName: row.lastName, email: row.email, password: row.password || 'Password123!', role: (row.role || 'student') as UserRole, phone: row.phone }))); const succeeded = imported.filter((result) => result.status === 'fulfilled').length; setActionMessage(`Imported ${succeeded} of ${rows.length} users.`); await usersQuery.refetch() }
  return <div className="user-page">
    <header className="user-page-heading"><div><p className="user-eyebrow">People / Directory</p><h1>User management</h1><p>Manage everyone who belongs to your institution.</p></div><div className="user-heading-actions"><div className="user-heading-stat"><Users size={18} /><span><strong>{meta?.total ?? '—'}</strong> total users</span></div><button className="user-primary-button" type="button" onClick={openCreate}><Plus size={16} /> Add user</button></div></header>
    {actionMessage && <div className="user-action-message">{actionMessage}<button type="button" onClick={() => setActionMessage('')} aria-label="Dismiss message"><X size={14} /></button></div>}
    <section className="user-toolbar"><label className="user-search"><Search size={16} /><input value={filters.search} onChange={(event) => setFilter('search', event.target.value)} placeholder="Search by name or email..." aria-label="Search users" />{filters.search && <button type="button" onClick={() => setFilter('search', '')} aria-label="Clear search"><X size={14} /></button>}</label><div className="user-filter"><Filter size={15} /><select value={filters.role} onChange={(event) => setFilter('role', event.target.value as UserRole | 'all')} aria-label="Filter by role">{roles.map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</select><ChevronDown size={14} /></div><div className="user-filter"><select value={filters.isActive} onChange={(event) => setFilter('isActive', event.target.value as UserFilters['isActive'])} aria-label="Filter by status"><option value="all">All status</option><option value="active">Active</option><option value="inactive">Inactive</option></select><ChevronDown size={14} /></div><div className="user-import-actions"><input ref={importInput} hidden type="file" accept=".csv,text/csv" onChange={importCsv} /><button type="button" className="user-outline-button" onClick={() => importInput.current?.click()}><Upload size={15} /> Import CSV</button><button type="button" className="user-outline-button user-template-button" onClick={downloadTemplate}><Download size={15} /> Template</button></div></section>
    <section className="user-table-panel"><div className="user-table-scroll"><table className="user-table"><thead><tr><th>User</th><th>Role</th><th>Contact</th><th>Status</th><th>Joined</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{usersQuery.isLoading ? <LoadingRows /> : usersQuery.isError ? <tr><td colSpan={6}><div className="user-state"><strong>Could not load users</strong><span>Check your session and API connection, then try again.</span><button type="button" onClick={() => usersQuery.refetch()}>Try again</button></div></td></tr> : users.length === 0 ? <tr><td colSpan={6}><div className="user-state"><strong>No users found</strong><span>Try a different search or filter.</span></div></td></tr> : users.map((user) => <tr key={user.id}><td><div className="user-identity"><div className={`user-avatar user-avatar--${user.role}`}>{user.firstName[0]}{user.lastName[0]}</div><div><strong>{user.firstName} {user.lastName}</strong><span>{user.email}</span></div></div></td><td><span className={`role-pill role-pill--${user.role}`}>{roleLabels[user.role]}</span></td><td><span className="user-contact">{user.phone || 'No phone added'}</span></td><td><span className={`status-pill ${user.isActive ? 'status-pill--active' : 'status-pill--inactive'}`}><i />{user.isActive ? 'Active' : 'Inactive'}</span></td><td><span className="joined-date">{new Date(user.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</span></td><td><div className="user-actions"><button className="user-more" type="button" onClick={() => openEdit(user)} aria-label={`Edit ${user.firstName} ${user.lastName}`}><Pencil size={15} /></button>{user.isActive && <button className="user-more user-more--danger" type="button" onClick={() => removeUser(user)} aria-label={`Deactivate ${user.firstName} ${user.lastName}`}><Trash2 size={15} /></button>}</div></td></tr>)}</tbody></table></div><footer className="user-pagination"><span>{meta && meta.total > 0 ? <>Showing <strong>{(meta.page - 1) * meta.limit + 1}-{Math.min(meta.page * meta.limit, meta.total)}</strong> of <strong>{meta.total}</strong></> : 'No users to display'}</span><div><button type="button" disabled={!meta || meta.page <= 1} onClick={() => setFilter('page', filters.page - 1)} aria-label="Previous page"><ChevronLeft size={16} /></button><span>Page {meta?.page ?? 1} of {meta?.pages || 1}</span><button type="button" disabled={!meta || meta.page >= meta.pages} onClick={() => setFilter('page', filters.page + 1)} aria-label="Next page"><ChevronRight size={16} /></button></div></footer></section>
    {isModalOpen && <UserModal user={editingUser} isSaving={isSaving} onClose={() => setIsModalOpen(false)} onSave={saveUser} />}
  </div>
}

function UserModal({ user, isSaving, onClose, onSave }: { user: UserRecord | null; isSaving: boolean; onClose: () => void; onSave: (input: UserInput) => Promise<void> }) {
  const [form, setForm] = useState<UserFormValues>(user ? { firstName: user.firstName, lastName: user.lastName, email: user.email, phone: user.phone ?? '', password: '', role: user.role } : blankForm)
  const [error, setError] = useState('')
  const updateField = <Key extends keyof UserFormValues>(key: Key, value: UserFormValues[Key]) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.firstName || !form.lastName || !form.email || (!user && !form.password)) { setError('Complete all required fields before saving.'); return } setError(''); await onSave({ ...form, password: form.password || undefined }) }
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="user-modal" role="dialog" aria-modal="true" aria-labelledby="user-modal-title"><header><div><p className="user-eyebrow">People / Directory</p><h2 id="user-modal-title">{user ? 'Edit user' : 'Add user'}</h2></div><button type="button" className="modal-close" onClick={onClose} aria-label="Close modal"><X size={18} /></button></header><form onSubmit={submit}><div className="modal-form-grid"><label className="modal-field"><span>First name *</span><input value={form.firstName} onChange={(event) => updateField('firstName', event.target.value)} /></label><label className="modal-field"><span>Last name *</span><input value={form.lastName} onChange={(event) => updateField('lastName', event.target.value)} /></label></div><label className="modal-field"><span>Email *</span><input type="email" value={form.email} onChange={(event) => updateField('email', event.target.value)} /></label><label className="modal-field"><span>Phone</span><input value={form.phone} onChange={(event) => updateField('phone', event.target.value)} /></label><div className="modal-form-grid"><label className="modal-field"><span>Role *</span><select value={form.role} onChange={(event) => updateField('role', event.target.value as UserRole)}>{roles.filter((role): role is UserRole => role !== 'all').map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</select></label><label className="modal-field"><span>{user ? 'New password' : 'Password *'}</span><input type="password" value={form.password} onChange={(event) => updateField('password', event.target.value)} placeholder={user ? 'Leave blank to keep current' : 'Minimum 8 characters'} /></label></div>{error && <p className="modal-error">{error}</p>}<footer><button type="button" className="user-cancel-button" onClick={onClose}>Cancel</button><button type="submit" className="user-primary-button" disabled={isSaving}>{isSaving && <LoaderCircle className="spin" size={15} />}{isSaving ? 'Saving...' : user ? 'Save changes' : 'Create user'}</button></footer></form></section></div>
}

function parseCsv(text: string): Array<Record<string, string>> { const lines = text.trim().split(/\r?\n/).filter(Boolean); if (lines.length < 2) return []; const headers = lines[0].split(',').map((header) => header.trim()); return lines.slice(1).map((line) => { const values = line.split(',').map((value) => value.trim().replace(/^"|"$/g, '')); return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ''])) }) }
function downloadTemplate() { const content = 'firstName,lastName,email,password,role,phone\nOlivia,Chen,olivia@example.edu,Password123!,student,555-0100\n'; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'text/csv' })); link.download = 'educore-users-template.csv'; link.click(); URL.revokeObjectURL(link.href) }
function LoadingRows() { return <>{Array.from({ length: 5 }, (_, index) => <tr key={index}><td colSpan={6}><div className="user-skeleton-row"><i /><i /><i /></div></td></tr>)}</> }
